config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/about'
  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, controllers: {
      sessions: 'admin_users/sessions'
    }

    # маршрут для админки
    namespace :admin do
      resources :products
      resources :orders, only: [:index]
      root to: 'home#index'
    end

    resources :users, only: [] do
      get :address, on: :collection
      patch :update_address, on: :collection
    end

    resources :users, only: %i[new create]
    post '/verify', to: 'users#verify', as: 'verify_user'
    delete '/logout', to: 'users#logout', as: 'logout'

    resources :products, only: %i[index show]
    resource :cart, only: [:show]
    resources :cart_items, only: %i[create update destroy]
    resources :orders, only: %i[create index show]
    get '/about', to: 'pages#about', as: 'about'

    root 'products#index'
  end

  # ActiveStorage можно монтировать вне scope — он не требует локали
  mount ActiveStorage::Engine => '/rails/active_storage'
end

app/models/product.rb
# frozen_string_literal: true

# Product represents an item that can be sold in the system.
# It may have an image attached to it.
#
# Associations:
# - has_one_attached :image: Allows a product to have a single image attached using ActiveStorage.
class Product < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validate :image_presence

  scope :active, -> { where(deleted_at: nil) }
  scope :deleted, -> { where.not(deleted_at: nil) }

  def soft_delete
    update(deleted_at: Time.current)
  end

  def deleted?
    deleted_at.present?
  end

  private

  def image_presence
    errors.add(:image, 'должно быть загружено') unless image.attached?
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  # Admin::ProductsController is responsible for managing the products in the admin panel.
  # This controller allows the admin user to perform CRUD (Create, Read, Update, Delete) operations
  # on the products available in the application.
  #
  # Actions:
  # - `index`: Displays a list of all products.
  # - `new`: Renders the form for creating a new product.
  # - `edit`: Renders the form for editing an existing product.
  # - `create`: Creates a new product.
  # - `update`: Updates an existing product.
  # - `destroy`: Deletes a product.
  #
  # @see Product
  class ProductsController < ApplicationController
    # Before actions
    before_action :authenticate_admin_user!
    before_action :set_product, only: %i[edit update destroy]
    layout 'admin'

    # GET /admin/products
    #
    # This action fetches and displays all the products in the admin panel.
    #
    # @return [Array<Product>] list of all products
    def index
      @products = Product.active.order(created_at: :asc, name: :asc) # Старые сверху, затем сортировка по имени
    end

    # GET /admin/products/new
    #
    # This action renders the form for creating a new product.
    #
    # @return [Product] the newly created product
    def new
      @product = Product.new
    end

    # GET /admin/products/:id/edit
    #
    # This action renders the form for editing an existing product.
    #
    # @param id [Integer] the ID of the product to be edited
    # @return [Product] the product to be edited
    def edit; end

    # POST /admin/products
    #
    # This action creates a new product based on the submitted form data.
    # If the product is saved successfully, it redirects to the product list page,
    # otherwise, it re-renders the new product form.
    #
    # @return [redirect] redirects to the admin products page if successful, renders new form if failed
    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path
      else
        render :new
      end
    end

    # PATCH/PUT /admin/products/:id
    #
    # This action updates an existing product with the submitted form data.
    # If the update is successful, it redirects to the product list page,
    # otherwise, it re-renders the edit product form.
    #
    # @param id [Integer] the ID of the product to be updated
    # @return [redirect] redirects to the admin products page if successful, renders edit form if failed
    def update
      if @product.update(product_params)
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    # DELETE /admin/products/:id
    #
    # This action deletes a product from the database.
    # After deletion, it redirects to the admin products page.
    #
    # @param id [Integer] the ID of the product to be deleted
    # @return [redirect] redirects to the admin products page after deletion
    def destroy
      @product.soft_delete
      redirect_to admin_products_path
    end

    private

    # Finds the product based on the given id from the params.
    #
    # @return [Product] the product to be used in edit, update, or destroy actions
    def set_product
      @product = Product.find(params[:id])
    end

    # Strong parameters to allow only permitted product attributes.
    #
    # @return [ActionController::Parameters] the permitted product parameters
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# ProductsController is responsible for managing the products in the application.
# It handles the display of products in the store, including showing a list of all products
# and displaying individual product details.
#
# Actions:
# - `index`: Displays a list of all products.
# - `show`: Displays the details of a specific product.
#
# @see Product
class ProductsController < ApplicationController
  # Displays a list of all products available in the store.
  #
  # This action fetches all products from the database and loads them to be displayed to the user.
  # It also loads the cart items to display them in the cart.
  #
  # @return [Array<Product>] list of all products
  def index
    @products = Product.active
                       .includes(image_attachment: :blob)
                       .order(created_at: :asc, name: :asc) # исключаем удалённые
    load_cart_items
  end

  # Displays the details of a specific product.
  #
  # This action finds a single product based on the provided ID in the parameters.
  #
  # @param id [Integer] the ID of the product to be displayed
  # @return [Product] the product details
  def show
    @product = Product.find(params[:id])
  end

  private

  # Strong parameters for product attributes.
  # Only allows the specified attributes to be passed in for a product.
  #
  # @return [ActionController::Parameters] the permitted product parameters
  def product_params
    params.require(:product).permit(:name, :price, :description, :weight, :image)
  end
end

app/views/products/_product.html.erb
<turbo-frame id="product-<%= product.id %>">
  <div class="card h-100 border-0 shadow-sm d-flex flex-column justify-content-between card-hover" style="transition: transform 0.3s ease;">
    
    <!-- Фото -->
    <% if product.image.attached? %>
      <%= image_tag url_for(product.image), width: 300, height: 300, class: "card-img-top", style: "object-fit: contain; padding: 10px;" %>
    <% else %>
      <%= image_tag "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='300' height='300'><rect width='100%' height='100%' fill='%23f8f9fa'/><text x='50%' y='50%' dominant-baseline='middle' text-anchor='middle' fill='%23666' font-size='20'>No Image</text></svg>", width: 300, height: 300, class: "card-img-top", style: "object-fit: contain; padding: 10px;" %>
    <% end %>



    <!-- Описание -->
    <div class="card-body text-center p-2">
      <h6 class="card-title mb-1 fw-bold"><%= product.name %></h6>
      <p class="card-text mb-2 text-muted small"><%= product.description %></p>
    </div>

    <!-- Кнопки -->
    <div class="p-2">
      <% if quantity > 0 && cart_item %>
  <div class="d-flex align-items-center gap-2 w-100">
    <%= button_to '-', cart_item_path(cart_item),
                    method: :patch,
                    params: { change: -1 },
                    data: { turbo_stream: true },
                    form_class: "w-50 m-0 p-0",
                    class: "btn custom-red-btn w-100 fw-bold d-flex align-items-center justify-content-center" %>

    <div class="fw-bold text-center"><%= quantity %></div>

    <%= button_to '+', cart_item_path(cart_item),
                    method: :patch,
                    params: { change: 1 },
                    data: { turbo_stream: true },
                    form_class: "w-50 m-0 p-0",
                    class: "btn custom-red-btn w-100 fw-bold d-flex align-items-center justify-content-center" %>
  </div>
<% else %>
  <%= form_with url: cart_items_path, method: :post, data: { turbo_stream: true } do %>
    <%= hidden_field_tag :product_id, product.id %>
    <%= submit_tag "#{product.price} ₽", class: "btn custom-red-btn w-100" %>
  <% end %>
<% end %>

    </div>

  </div>
</turbo-frame>

app/views/products/index.html.erb
<div class="row justify-content-center g-2">
  <% @products.each do |product| %>
    <% cart_item = @cart_items.find { |item| item.product_id == product.id } %>
    <div class="col-md-3">
      <%= render partial: 'products/product', locals: {
            product: product,
            quantity: @cart_items_hash[product.id] || 0,
            cart_item: cart_item
          } %>
    </div>
  <% end %>
</div>




<br>
 <footer class="bg-light border-top m-0 p-0">
  <div class="w-100 d-flex flex-wrap">
    
    <!-- Карта -->
    <div class="flex-grow-1" style="min-width: 300px;">
      <div class="ratio ratio-4x3">
        <iframe
          src="https://yandex.ru/map-widget/v1/?ll=37.628490%2C55.759711&z=16&text=Москва%2C%20ул.%20Большая%20Лубянка%2C%2012%2F1"
          width="100%" height="100%" frameborder="0" style="border:0;">
        </iframe>
      </div>
    </div>

    <!-- Контакты -->
    <div class="d-flex flex-column justify-content-center p-3" style="min-width: 300px;">
      <h5 class="fw-bold mb-2"><%= t('about_us.title') %></h5>
      <p class="mb-1"><%= t('about_us.adress') %>: г. Москва, ул. Сушиная, д. 8</p>
      <p class="mb-1"><%= t('about_us.phone') %>: +7 (999) 123-45-67</p>
      <p class="mb-1"><%= t('about_us.time') %></p>

      <%= link_to t('buttons.about'), about_path, class: "btn btn-outline-secondary btn-sm mt-2", style: "max-width: 200px;" %>
    </div>

  </div>
</footer>

  </div>
</footer>

app/views/products/show.html.erb
<%= form_with url: cart_items_path, method: :post, remote: true do %>
  <%= hidden_field_tag :product_id, product.id %>
  <%= submit_tag t('buttons.add_to_cart'), class: "btn btn-success" %>
<% end %>