config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/about'
  scope '(:locale)', locale: /en|ru/ do
    devise_for :admin_users, controllers: {
      sessions: 'admin_users/sessions'
    }

    # маршрут для админки
    namespace :admin do
      resources :products
      resources :orders, only: [:index]
      root to: 'home#index'
    end

    resources :users, only: [] do
      get :address, on: :collection
      patch :update_address, on: :collection
    end

    resources :users, only: %i[new create]
    post '/verify', to: 'users#verify', as: 'verify_user'
    delete '/logout', to: 'users#logout', as: 'logout'

    resources :products, only: %i[index show]
    resource :cart, only: [:show]
    resources :cart_items, only: %i[create update destroy]
    resources :orders, only: %i[create index show]
    get '/about', to: 'pages#about', as: 'about'

    root 'products#index'
  end

  # ActiveStorage можно монтировать вне scope — он не требует локали
  mount ActiveStorage::Engine => '/rails/active_storage'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiDelivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
     <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">

  </head>
  <body>
<%= render 'shared/flash' %>
    <div class="container-fluid px-4 py-3">
      <div class="container">
        <header class="d-flex justify-content-center py-3 ">
          <ul class="nav nav-pills gap-4">
              <a href="<%= admin_root_path %>" class="text-decoration-none">
                <span class="logo-title">SUSHIIII</span>
              </a>
            
            <li>
              <%= link_to t('buttons.add_products'), new_admin_product_path, class: 'btn custom-red-btn w-100 me-5' %>
            </li>
           <li>
            <%= link_to t('buttons.orders'), admin_orders_path, class: "btn custom-red-btn w-100 me-5" %>

            </li>

            <li class="nav-item">
              <!-- Блок пользователя -->

                <div class="d-flex justify-content-end gap-3 mb-3">
                <% if admin_user_signed_in? %>
                  <%= button_to t('buttons.log_out'), destroy_admin_user_session_path, method: :delete, class: 'btn custom-red-btn w-100 me-5' %>
                <% end %>

                <%= link_to (I18n.locale == :en ? "RU" : "EN"),
                            url_for(locale: I18n.locale == :en ? :ru : :en),
                            class: "btn custom-red-btn text-center px-4",
                            style: "min-width: 80px;" %>
              </div>  
              </div>
            </li>
          </ul>
        </header>
      </div>
    </div>
  
  
    <%= yield %>
    <%= render 'carts/cart_modal' %>
    <!-- Модальное окно для корзины -->
    <div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="cartModalLabel">Ваша корзина</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
            <turbo-frame id="cart-frame">
              <!-- Корзина загрузится сюда -->
            </turbo-frame>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SushiDelivery</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">

</head>

<body>
  <%= render 'shared/flash' %>  
  <!-- Главный контейнер -->
  <div class="main-wrapper">



    <!-- Header -->
    
    <header class="d-flex flex-column gap-2 gap-md-0 flex-md-row align-items-center justify-content-between py-3 mb-4">
  <!-- Логотип (мобильный) -->
  <!-- Логотип и адрес для мобильных -->
<div class="w-100 d-block d-md-none text-center mb-2">
  <a href="<%= root_path %>" class="d-inline-flex link-body-emphasis text-decoration-none mb-1">
    <span class="logo-title">SUSHIIII</span>
  </a>

  <% if logged_in? && current_user.address.present? %>
    <div class="address-box mx-auto d-inline-block mt-1" id="edit-address-btn" data-bs-toggle="modal" data-bs-target="#addressModal" role="button">
      <small class="text-muted"><%= t('buttons.delivery_address')%>:</small>
      <strong><%= current_user.address %></strong>
    </div>
  <% end %>
</div>

  <!-- Логотип + адрес (десктоп) -->
  <div class="d-none d-md-flex align-items-center gap-3">
    <a href="<%= root_path %>" class="d-inline-flex link-body-emphasis text-decoration-none">
      <span class="logo-title">SUSHIIII</span>
    </a>

    <% if logged_in? %>
      <div class="address-box" id="edit-address-btn" data-bs-toggle="modal" data-bs-target="#addressModal" role="button">
        <% if current_user.address.present? %>
          <small class="text-muted"><%= t('buttons.delivery_address')%>:</small>
          <strong><%= current_user.address %></strong>
        <% else %>
          <strong></strong>
        <% end %>
      </div>
    <% end %>
  </div>

      <!-- Корзина и авторизация -->
      <div class="d-flex align-items-center gap-3">
        <!-- Корзина -->
        <a href="#"
          class="text-decoration-none text-dark d-flex align-items-center position-relative"
          data-bs-toggle="modal"
          data-bs-target="#cartModal">
          <i class="bi bi-basket fs-3 fs-sm-2 fs-md-1"></i>
          <span id="cart-count" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            <%= @cart_items_count || 0 %>
          </span>
        </a>
        


        <!-- Вход / Выход -->
        <% if logged_in? %>
        <%= button_to t('buttons.order_link'), orders_path,method: :get, class: 'btn custom-red-btn w-100 me-5' %>
        
          <%= button_to t('buttons.log_out'), logout_path, method: :delete, class: "btn custom-red-btn w-100 me-5", form_class: "d-inline" %>
        <% else %>
          <%= button_to t('buttons.log_in'), new_user_path, method: :get, class: "btn custom-red-btn w-100 me-5", form_class: "d-inline" %>
        <% end %>
        <%= link_to (I18n.locale == :en ? "RU" : "EN"),
            url_for(locale: I18n.locale == :en ? :ru : :en),
            class: "btn custom-red-btn text-center px-4", style: "min-width: 80px;" %>

      </div>
    </header>

    <!-- Контент -->
    <%= yield %>

  </div>

  <!-- Модалка корзины -->
  <%= render 'carts/cart_modal' %>

  <!-- Модалка адреса -->
  <% if logged_in? %>
    <div class="modal fade" id="addressModal" tabindex="-1" aria-labelledby="addressModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addressModalLabel"><%= t('adress.title')%></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
            <%= form_with model: current_user, url: update_address_users_path, method: :patch, local: true do |f| %>
              <div class="mb-3">
                <%= f.label :address, t('adress.address'), class: 'form-label' %>
                <%= f.text_field :address, class: 'form-control', value: current_user.address %>
              </div>
              <div class="text-end">
                <%= f.submit t('adress.save'), class: 'btn custom-red-btn w-100 me-5' %>
                
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</body>
</html>